Weather
Postmen-At-Work/GameOn pull request #18
Opened 2023-04-08 21:04 UTC by itsbrotherdan

2023-04-08 21:11 UTC, copelka commented on client/components/Event.jsx
> +  const API_URL = `https://api.open-meteo.com/v1/forecast?daily=weathercode&start_date=2023-04-10&end_date=2023-04-10&timezone=auto&latitude=${props.eventData.coordinates[1]}&longitude=${props.eventD
API calls should be made on the server side

2023-04-08 21:12 UTC, copelka requested changes
API calls should be made on the server side

2023-04-08 21:13 UTC, matthewpmi approved these changes
lgtm - nevermind

2023-04-08 21:41 UTC, matthewpmi approved these changes
wait!

2023-04-08 21:42 UTC, opsparkbtc approved these changes

2023-04-08 21:43 UTC, kevinklein09 approved these changes

2023-04-09 00:52 UTC, matthewpmi approved these changes
okay now this is good

2023-04-09 00:53 UTC, kevinklein09 approved these changes

2023-04-09 00:53 UTC, merged